### ISSUE TITLE
Check TB303 Filter

### ISSUE THREAD

**Issue by aure** [AudioKit/SoundpipeAudioKit#1]
An anonymous GitHub user who is familiar with the TB303 filter were trying to implement has stated that something is wrong with it. Not sure if its at the DSP level of Soundpipe or higher up in the C++ or Swift layers, but its worth checking. The original issue is [here](https://github.com/AudioKit/AudioKit/issues/2520).

**Comment by PaulBatchelor** [comment]
The 303 filter we have isn't an exact recreation of the circuit. It only
approximates some of the characteristics. It's a TB303-ish filter.

Maybe that should be clarified in the docs somewhere?

Other than that, there's nothing actionable to be done here, unless someone
is willing to implement a better filter...

**Comment by PaulBatchelor** [comment]
If anyone wants to build a more accurate 303 filter, this page might be a
good start: http://www.timstinchcombe.co.uk/index.php?pge=diode2

Massive transfer function, so I don't know how practical it would be to
use. A more generalized diode ladder filter may get the job done (the
pirkle diode ladder filter, for example).
