### ISSUE TITLE
PitchTap How to identify the frequency of guitar polyphony？

### ISSUE THREAD

**Issue by benben-hello** [AudioKit/SoundpipeAudioKit#12]
I want to do guitar microphone recognition, single tone can be identified, but how to identify multiple tones?

**Comment by aure** [comment]
You can't do that with SoundpipeAudioKit.

**Comment by benben-hello** [comment]
What should I do? Is there a library recommendation? Thank you very much!

**Comment by emurray2** [comment]
> What should I do? Is there a library recommendation? Thank you very much!

This looks promising [https://github.com/jaym910/polyphonic_track](https://github.com/jaym910/polyphonic_track).

If you don't need it to be real-time, `librosa` is another great library for detecting pitch sets and key signatures.
