### ISSUE TITLE
Set Limiter and Noise gate with AudioEngine.InputNode

### ISSUE THREAD

**Issue by infocodiste** [AudioKit/SoundpipeAudioKit#13]
Please let us know how to implement limiter and noise gate from new SDK. we tried below solution for noise gate but it's not included in new SDK.
https://stackoverflow.com/questions/47601246/audiokit-noise-gate

**Comment by aure** [comment]
Is this a request for us to do your work for you for free?

**Comment by infocodiste** [comment]
Thanks for asking @aure . Looks like there is some misunderstanding in wording. We are asking to check if its feasible in your current Architecture or Architecture level its not feasible ?

**Comment by emurray2** [comment]
> Thanks for asking @aure . Looks like there is some misunderstanding in wording. We are asking to check if its feasible in your current Architecture or Architecture level its not feasible ?

Yes, it's still feasible. You may want to check out AudioKit/AudioKit and use the `AmplitudeTap` https://github.com/AudioKit/AudioKit/blob/main/Sources/AudioKit/Taps/AmplitudeTap.swift .

More documentation is available at https://audiokit.io and in the wiki https://github.com/AudioKit/AudioKit/wiki
