### ISSUE TITLE
PitchTap cpu pegged at 40-50% cpu

### ISSUE THREAD

**Issue by quantamrhino** [AudioKit/SoundpipeAudioKit#23]
Referencing audiokit issue https://github.com/AudioKit/AudioKit/issues/1753 

PitchTap uses huge CPU power - about 42-48% on older devices, ~30-35% on newer devices (11 and higher). 
I tried wrapping my head around the C code and it's all going over my head.
I have absolutely no background in any of this stuff of work - I is just a simple front-end person making a simple app :-)
any app using mic analysis will face UI stutters, audio issues, even in a simple case lime mine.

**Comment by aure** [comment]
Not sure what can be done about this.
