### ISSUE TITLE
Swift Package Manger can't find SoundpipeAudioKit

### ISSUE THREAD

**Issue by lsamaria** [AudioKit/SoundpipeAudioKit#24]
Swift Package Manager can't locate the this library. I tried both `https://swiftpackageindex.com/AudioKit/collection.json` and `https://github.com/AudioKit/SoundpipeAudioKit`

![Screen Shot 2022-08-11 at 6 07 43 PM](https://user-images.githubusercontent.com/15787990/184250901-e9569ee9-df97-4550-9eac-1ccf01e3edd0.png)

![Screen Shot 2022-08-11 at 5 55 31 PM](https://user-images.githubusercontent.com/15787990/184250570-2cebe017-10a0-4887-aaee-cb52754e6015.png)

![Screen Shot 2022-08-11 at 6 08 09 PM](https://user-images.githubusercontent.com/15787990/184250926-0003e0a2-c1a9-42e4-aa5b-fec8e4b81e54.png)

![Screen Shot 2022-08-11 at 5 53 25 PM](https://user-images.githubusercontent.com/15787990/184250589-04b11439-ed26-424b-987b-7d4e4d9d9f40.png)

**Comment by aure** [comment]
Download the AudioKItCookbook, it uses SoundpipeAudioKit

**Comment by lsamaria** [comment]
ok, I'll try it now, thanks!

**Comment by lsamaria** [comment]
Same issue. I tried `https://github.com/AudioKit/Cookbook/` and I tried with my Xcode GitHub login to use SSH and also HTTPS

![Screen Shot 2022-08-11 at 6 31 17 PM](https://user-images.githubusercontent.com/15787990/184253717-c8418cad-b581-403f-912f-ad49ad8b771a.png)

![Screen Shot 2022-08-11 at 6 30 42 PM](https://user-images.githubusercontent.com/15787990/184253743-ff2ce5ed-731c-4460-8c17-4bba43666d68.png)

**Comment by aure** [comment]
That's not what I meant. Clone the cookbook and see that it uses SoundpipeAudioKit within it.  This is not an issue with our package, I'm going to close it.

**Comment by lsamaria** [comment]
ok, thanks!

**Comment by lsamaria** [comment]
@aure I found the issue. It's because I'm using Xcode 12.  Once I used a different computer that has `Xcode 13` `https://swiftpackageindex.com/AudioKit/collection.json` was imported and I was able to access `SoundpipeAudioKit`. Maybe you should add a warning on the home page to let users who are running Xcode 12 that they might have problems with this dependency.

Btw the reason I have Xcode 12 is because it's on a 2012 MacBook Pro which isn't compatible with Xcode 13. 

Again, thanks for your help! :)
