### ISSUE TITLE
SourcePackages/checkouts/SoundpipeAudioKit/Sources/SoundpipeAudioKit/PitchTap.swift:42:66: error build: Editor placeholder in source file 

### ISSUE THREAD

**Issue by wyy511511** [AudioKit/SoundpipeAudioKit#32]
### macOS Version(s) Used to Build

macOS 12 Monterey

### Xcode Version(s)

Xcode 14

### Description

When I try to build my project, it remind me that "SourcePackages/checkouts/SoundpipeAudioKit/Sources/SoundpipeAudioKit/PitchTap.swift:42:66: error build: Editor placeholder in source file". Then I git clone the newest one and change read-only file and add `   public init(_ input: Node, bufferSize: UInt32 = 4096, handler: @escaping Handler) {
        self.handler = handler
        super.init(input, bufferSize: bufferSize, callbackQueue: DispatchQueue.main)
    }` , exact ` callbackQueue: DispatchQueue.main` Then I fix it. I am not sure why so just report this.

**Comment by wyy511511** [comment]
the version is 5.5.1

**Comment by wtholliday** [comment]
Can't repro. Try resetting your package caches.

**Comment by leynercastillo** [comment]
I have the same issue after clean spm cache on 5.5.3. Looks like a common error.

**Comment by aure** [comment]
No, the actual mistake is that these releases were not properly tied the appropriate version of AudioKit. It's grabbing the version "from: 5.5.0" which means it will grab v6. If you change it grab exactly 5.5.3 or whatever, it should work. Sorry, we'll fix that in the future. For now if you grab the latest source code it should work.
