### ISSUE TITLE
AmplitudeEnvelope doesn't reset trigger on MIDI_NOTE_OFF

### ISSUE THREAD

**Issue by emurray2** [AudioKit/SoundpipeAudioKit#9]
The `AmplitudeEnvelope` doesn't get any input audio from `MIDISampler`. However, other nodes such as `ZitaReverb` do. This can be confirmed by adding `printf("%.2f\n", *in);` to the first line of the `sp_adsr_compute` function. The value of `*in` changes in `ZitaReverb`, but for `AmplitudeEnvelope`, it stays at `0.0`.

Steps to reproduce:
1. Create sampler node `sampler = MIDISampler()`
2. Set sampler amplitude `sampler.amplitude = 1`
3. Create adsr `adsr = AmplitudeEnvelope(sampler)`
4. Set the engine output `engine.output = adsr`
5. Start AudioKit `try? engine.start()`
6. AudioKit starts successfully, but no sound happens when the sampler is played

Expected behavior:
I would expect the `AmplitudeEnvelope` to act as the other Soundpipe nodes and continue to pass audio through it.

Details:
 - Type: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
 - Processor: 2.3 GHz Quad-Core Intel Core i7
 - OS: macOS Big Sur 11.5
 - SoundpipeAudioKit Version: latest `develop` branch: 8c01594681b4e12acd86f715cada316bdf8be1cf

I'll work on trying to fix this, but just wanted to leave it here so people are aware. The [AudioKit/Cookbook](https://github.com/AudioKit/Cookbook/tree/develop) `AmplitudeEnvelope` is also a bit broken. The oscillator sound gets passed through, but the ADSR widget has no effect on the sound. It might be worth opening up an issue there unless the fix for this makes it work again.

**Comment by emurray2** [comment]
I see the problem now. I misunderstood how the module actually works. I didn't realize it needs MIDI input to trigger, so I added the following lines to my `KeyboardDelegate` methods:

```
func noteOn(note: MIDINoteNumber) {
        if notesToDisable.contains(note) {
            // Do nothing --- don't play the note
        } else {
            sampler.play(noteNumber: note, velocity: 100, channel: 0)
            adsr.scheduleMIDIEvent(event: MIDIEvent(noteOn: note, velocity: 100, channel: 0), offset: 0)
        }
    }
    func noteOff(note: MIDINoteNumber) {
        sampler.stop(noteNumber: note, channel: 0)
        adsr.scheduleMIDIEvent(event: MIDIEvent(noteOff: note, velocity: 0, channel: 0), offset: 0)
    }
```
The adsr now schedules a midi event when it receives note on/note off, which starts the trigger. However, there was no handling for resetting the trigger, so I will add that. Also, there are some switch cases in the `adsr.c` that seem to be left un-implemented. I will work on finishing those if needed.

For example, `case DECAY:` on line 86 of `adsr.c` in the Soundpipe modules folder is just an empty block.

**Comment by PaulBatchelor** [comment]
The DECAY case switch works as intended: it carries over to RELEASE (note
the lack of a break statement). I believe I did that because they were
basically doing the same thing.

**Comment by emurray2** [comment]
@PaulBatchelor Gotcha. I just saw the `pole = tau2pole(sp, p, p->dec);` on line 81 which makes sense. It seems the MIDI trigger was the only thing which was missing then.

**Comment by emurray2** [comment]
Yep, it works! I just needed to make the velocity of the sampler 127. Otherwise, the out sample would never be greater than 0.99. But now it works great.
